"""
Email dataset for triage environment.
Three tasks of increasing difficulty.
Each email has a ground-truth label and priority.
"""

TASKS = {
    "easy": {
        "description": "Triage 5 clearly distinct emails — spam is obvious, urgent is explicit.",
        "difficulty": "easy",
        "emails": [
            {
                "email_id": "e1",
                "subject": "WINNER! Claim your $1,000,000 prize NOW!!!",
                "sender": "noreply@prize-scam.xyz",
                "body": "Congratulations! You have been selected as our lucky winner. Click here immediately to claim your prize before it expires!",
                "timestamp": "2024-01-15T08:00:00",
                "ground_truth_label": "spam",
                "ground_truth_priority": 5,
            },
            {
                "email_id": "e2",
                "subject": "URGENT: Server is down — production outage",
                "sender": "alerts@company.com",
                "body": "CRITICAL: Our main production server went down at 07:55 AM. Users cannot access the platform. Engineering team needed immediately.",
                "timestamp": "2024-01-15T08:05:00",
                "ground_truth_label": "urgent",
                "ground_truth_priority": 1,
            },
            {
                "email_id": "e3",
                "subject": "Team lunch this Friday?",
                "sender": "colleague@company.com",
                "body": "Hey! Thinking of organizing a team lunch this Friday around 1pm. Let me know if you're interested. No pressure!",
                "timestamp": "2024-01-15T09:00:00",
                "ground_truth_label": "normal",
                "ground_truth_priority": 4,
            },
            {
                "email_id": "e4",
                "subject": "Q4 Budget Proposal — needs your approval",
                "sender": "finance@company.com",
                "body": "Hi, please review and approve the attached Q4 budget proposal by end of week. This is required before we can proceed with vendor contracts.",
                "timestamp": "2024-01-15T09:30:00",
                "ground_truth_label": "important",
                "ground_truth_priority": 2,
            },
            {
                "email_id": "e5",
                "subject": "Your newsletter subscription",
                "sender": "newsletter@techdigest.com",
                "body": "This week in tech: AI updates, new framework releases, and a roundup of the top GitHub repos. Enjoy your weekly digest!",
                "timestamp": "2024-01-15T10:00:00",
                "ground_truth_label": "normal",
                "ground_truth_priority": 5,
            },
        ],
    },

    "medium": {
        "description": "Triage 7 emails where urgency requires reading context carefully.",
        "difficulty": "medium",
        "emails": [
            {
                "email_id": "m1",
                "subject": "Follow-up on yesterday's meeting",
                "sender": "client.partner@bigcorp.com",
                "body": "Hi, just wanted to follow up on our meeting. We're leaning toward signing the contract but have a few questions about SLA guarantees. Can we set up a quick call this week? Our legal team needs answers by Thursday.",
                "timestamp": "2024-01-15T08:10:00",
                "ground_truth_label": "urgent",
                "ground_truth_priority": 1,
            },
            {
                "email_id": "m2",
                "subject": "Re: Re: Re: Office supplies order",
                "sender": "admin@company.com",
                "body": "Confirming that the pens and notebooks have been ordered. Should arrive next Tuesday. Let me know if you need anything else.",
                "timestamp": "2024-01-15T08:20:00",
                "ground_truth_label": "normal",
                "ground_truth_priority": 5,
            },
            {
                "email_id": "m3",
                "subject": "Security alert: unusual login attempt",
                "sender": "security@company.com",
                "body": "We detected a login attempt to your account from an unrecognized device in Romania at 3:12 AM. If this was not you, please reset your password immediately and contact IT.",
                "timestamp": "2024-01-15T08:30:00",
                "ground_truth_label": "urgent",
                "ground_truth_priority": 1,
            },
            {
                "email_id": "m4",
                "subject": "Invitation: Webinar on cloud cost optimization",
                "sender": "events@cloudprovider.com",
                "body": "Join us for a free 1-hour webinar on reducing your cloud bills by up to 40%. Register now — spots are limited.",
                "timestamp": "2024-01-15T09:00:00",
                "ground_truth_label": "normal",
                "ground_truth_priority": 4,
            },
            {
                "email_id": "m5",
                "subject": "Performance review — your input needed",
                "sender": "hr@company.com",
                "body": "Hi, as part of our annual review cycle, we need you to complete the self-assessment form by Jan 20. Please log in to the HR portal. This affects your performance rating.",
                "timestamp": "2024-01-15T09:15:00",
                "ground_truth_label": "important",
                "ground_truth_priority": 2,
            },
            {
                "email_id": "m6",
                "subject": "Free iPhone 15 — limited offer",
                "sender": "offers@win-gadgets.ru",
                "body": "You've been pre-selected! Fill out this 30-second form to claim your FREE iPhone 15. Offer expires in 2 hours!",
                "timestamp": "2024-01-15T09:45:00",
                "ground_truth_label": "spam",
                "ground_truth_priority": 5,
            },
            {
                "email_id": "m7",
                "subject": "Deployment scheduled for tonight — please review",
                "sender": "devops@company.com",
                "body": "We have a major infrastructure migration scheduled for tonight at 11 PM. Please review the runbook and confirm you're available for on-call support. Rollback plan is attached.",
                "timestamp": "2024-01-15T10:00:00",
                "ground_truth_label": "important",
                "ground_truth_priority": 2,
            },
        ],
    },

    "hard": {
        "description": "Triage 10 emails with subtle cues, ambiguous senders, and mixed signals.",
        "difficulty": "hard",
        "emails": [
            {
                "email_id": "h1",
                "subject": "Quick question",
                "sender": "j.smith@gmail.com",
                "body": "Hey, do you have 10 minutes to chat? Something came up.",
                "timestamp": "2024-01-15T07:55:00",
                "ground_truth_label": "important",
                "ground_truth_priority": 2,
            },
            {
                "email_id": "h2",
                "subject": "Invoice #4521 — Payment overdue",
                "sender": "billing@legalfirm-associates.com",
                "body": "This is a formal notice that invoice #4521 for $12,400 is now 30 days overdue. Failure to pay within 7 days will result in legal proceedings. Please contact us immediately.",
                "timestamp": "2024-01-15T08:00:00",
                "ground_truth_label": "urgent",
                "ground_truth_priority": 1,
            },
            {
                "email_id": "h3",
                "subject": "Thoughts on the new roadmap?",
                "sender": "ceo@company.com",
                "body": "Hi, I've been thinking about the product roadmap we discussed last quarter. Would love your perspective — no rush, just when you get a chance.",
                "timestamp": "2024-01-15T08:10:00",
                "ground_truth_label": "important",
                "ground_truth_priority": 2,
            },
            {
                "email_id": "h4",
                "subject": "Your account has been suspended",
                "sender": "support@paypa1-secure.net",
                "body": "We have suspended your account due to suspicious activity. Click here to verify your identity and restore access within 24 hours.",
                "timestamp": "2024-01-15T08:15:00",
                "ground_truth_label": "spam",
                "ground_truth_priority": 5,
            },
            {
                "email_id": "h5",
                "subject": "Data breach notification — confidential",
                "sender": "legal@company.com",
                "body": "This is a confidential notification. Our security team has identified a potential data breach affecting customer records. A cross-functional response team needs to convene today at 2 PM. Please confirm attendance.",
                "timestamp": "2024-01-15T08:20:00",
                "ground_truth_label": "urgent",
                "ground_truth_priority": 1,
            },
            {
                "email_id": "h6",
                "subject": "Re: Partnership proposal",
                "sender": "partnerships@startup-xyz.io",
                "body": "Thanks for your interest! We'd love to explore a partnership. Our platform integrates with yours natively. Happy to send over a detailed deck and schedule a demo.",
                "timestamp": "2024-01-15T08:45:00",
                "ground_truth_label": "normal",
                "ground_truth_priority": 3,
            },
            {
                "email_id": "h7",
                "subject": "Compliance deadline — GDPR audit",
                "sender": "compliance@company.com",
                "body": "Reminder: The external GDPR audit is scheduled for January 22nd. All department heads must submit their data processing records by January 19th. Non-compliance may result in regulatory penalties.",
                "timestamp": "2024-01-15T09:00:00",
                "ground_truth_label": "urgent",
                "ground_truth_priority": 1,
            },
            {
                "email_id": "h8",
                "subject": "Great article I thought you'd enjoy",
                "sender": "friend@gmail.com",
                "body": "Hey! Saw this article about distributed systems and immediately thought of you. Hope you're doing well. Let's catch up soon!",
                "timestamp": "2024-01-15T09:30:00",
                "ground_truth_label": "normal",
                "ground_truth_priority": 5,
            },
            {
                "email_id": "h9",
                "subject": "AWS bill spike — 340% increase this month",
                "sender": "aws-billing@amazon.com",
                "body": "Your estimated AWS bill for this month is $8,420, compared to $1,920 last month. Unusual usage detected in EC2 and S3. Review your cost explorer for details.",
                "timestamp": "2024-01-15T09:45:00",
                "ground_truth_label": "urgent",
                "ground_truth_priority": 1,
            },
            {
                "email_id": "h10",
                "subject": "Lunch & Learn — ML in production (optional)",
                "sender": "learning@company.com",
                "body": "Join us for an optional Lunch & Learn session on deploying ML models in production. Friday 12–1 PM. Food provided. RSVP by Thursday.",
                "timestamp": "2024-01-15T10:00:00",
                "ground_truth_label": "normal",
                "ground_truth_priority": 5,
            },
        ],
    },
}
